apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engineer-service
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
    rollingUpdate:
      maxUnavailable: 25%  # Maximum unavailable pods during update
      maxSurge: 25%  # Maximum additional pods to create during update
  template:
    metadata:
      labels:
        app:  engineer-service
    spec:
      containers:
        - name:  engineer-service
          image: steven8519/engineer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
