apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineer-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: engineer-service
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  engineer-service
    spec:
      containers:
        - name:  engineer-service
          image: steven8519/engineer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
