apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engineer-service
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app:  engineer-service
    spec:
      containers:
        - name:  engineer-service
          image: steven8519/engineer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
