spring:
  datasource:
    url: jdbc:postgresql://172.232.19.199:5432/engineer
    username: engineer25
    password: thewordistheword
  jpa:
    hibernate:
      ddl-auto: update  # Set your desired Hibernate DDL behavior
    show-sql: true  # Set to true for debugging, but false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true