spring:
  datasource:
    url: jdbc:postgresql://https://48b1c5ac-a5f3-4e84-a940-431450f9e747.us-ord-1.linodelke.net:5432/engineer
    driverClassName: org.h2.Driver
    username: engineer25
  jpa:
    hibernate:
      ddl-auto: update  # Set your desired Hibernate DDL behavior
    show-sql: true  # Set to true for debugging, but false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true